spring:
  application:
    name: test-service-2
logging:
  level:
    org:
      springframework:
        security: DEBUG
security:
  oauth2:
    client:
      clientId: test-service-2
      clientSecret: test
      accessTokenUri: http://localhost:5000/oauth/token
      grant-type: client_credentials
      scope: all
    resource:
      user-info-uri: http://localhost:5000/users/current
server:
  port: 8081
eureka:
  client:
    service-url:
      defaultZone: http://localhost:5001/eureka/
