spring:
  application:
    name: auth
  data:
    mongodb:
      host: localhost
      database: cinemausers
      port: 27017
server:
  port: 5000
logging:
  level:
    org:
      springframework:
        security: DEBUG
eureka:
  client:
    service-url:
      defaultZone: http://localhost:5001/eureka/
