spring:
  application:
    name: auth
  data:
    mongodb:
      host: localhost
      database: cinemausers
      port: 27017
server:
  port: 5000
cors:
  origin: '*'
logging:
  level:
    org:
      springframework:
        security: DEBUG
