spring:
  application:
    name: hall-service
  datasource:
    url: jdbc:mysql://localhost:3306/hall_mcs
    username: garro
    password: yiZ#gbgVR&HaKd2@GUHk^Vr.
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: validate
security:
  oauth2:
    client:
      clientId: hall-service
      clientSecret: test
      accessTokenUri: http://localhost:5000/oauth/token
      grant-type: client_credentials
      scope: all
    resource:
      user-info-uri: http://localhost:5000/users/current
flyway:
  baseline-on-migrate: true
logging:
  level:
    org:
      hibernate: DEBUG
server:
  port: 8083
eureka:
  client:
    service-url:
      defaultZone: http://localhost:5001/eureka/