spring:
  application:
    name: gateway-service
server:
  port: 5002
eureka:
  client:
    service-url:
      defaultZone: http://localhost:5001/eureka/
security:
  oauth2:
    client:
      clientId: gateway-service
      clientSecret: test
      accessTokenUri: http://localhost:5000/oauth/token
      grant-type: client_credentials
      scope: all
    resource:
      user-info-uri: http://localhost:5000/users/current
zuul:
  ignored-services: '*'
  routes:
    auth:
      url: http://localhost:5000
    test-service-1:
      url: http://localhost:8080
    test-service-2:
      url: http://localhost:8081
